spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/giftit
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /giftit

logging:
  level:
    ROOT: DEBUG

#urls:
#  items: http://iframe.ly/api/iframely?url=...&api_key=1a3f50a29205bf7ec89c4f&_showcaption=true
#
