spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/giftit
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: has been removed for security purposes
#    password: has been removed for security purposes
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /giftit

logging:
  level:
    ROOT: DEBUG

