spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/giftit
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /giftit

logging:
  level:
    ROOT: DEBUG

urls:
  url1: iframe.ly/api/iframely?url=
  url2: &api_key=1a3f50a29205bf7ec89c4f
